@startuml
'図に表示する要素を定義
actor User as ユーザー
participant ブラウザ
participant Server as サーバー

'処理に連番を自動付与
autonumber

'noteで図の中にコメントを付与
'シングルクォートで図には反映されないコメントを書ける
note over ユーザー:メールとパスワードを入力する
ユーザー->ブラウザ:ログイン情報を渡す

'直線の矢印は -> 直線はリクエストを表す
note over ブラウザ:サーバーに確認してもらう
ブラウザ->サーバー:認証情報を送信

note over サーバー:DBの情報から本人チェック
サーバー->サーバー:ユーザー情報を確認

'点字の矢印は --> 点線はレスポンスを返す
サーバー-->ブラウザ:結果を返す
ブラウザ-->ユーザー:「成功」「失敗」を表示
@enduml